### ISSUE TITLE
can't install extension

### ISSUE THREAD

**Issue by drunkatheist** [dzaouch/fanogames#9]
I'm having some trouble installing the extension. I've downloaded the zip file and extracted folder "fanogames-master" which I then tried to drag and drop into my extensions tab in chrome as shown in the gif. Nothing happens when I do this, no error messages and no indication that the extension has been added. The drag and drop method has worked for other extensions and seems to at least be recognizing files that I try to add this way, since if I try to add the fanogames-master zip file, it returns the error message "Failed to load extension... could not unzip..." etc and then leaves error message "Could not load manifest". I've checked that my chrome is up to date.

I'm hoping I can get this working because I'm really interested in this extension, enough that if I can't get yours to work I plan to try to make one myself. Thanks for making this!

**Comment by ncla** [comment]
Alternatively you can try going to `chrome://extensions/` page, enabling 'Developer mode' and Load unpacked extension (before you must extract the zip file to somewhere).

**Comment by drunkatheist** [comment]
I've tried this as well. The result is exactly the same, no error message and no indication that anything has happened.

**Comment by dzaouch** [comment]
You have to extract the zip first, then drag and drop the extracted folder
to the extension tab.

2016-02-01 23:39 GMT+01:00 drunkatheist <notifications@github.com>:

> I've tried this as well. The result is exactly the same, no error message
> and no indication that anything has happened.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dzaouch/fanogames/issues/9#issuecomment-178235786>.
>



-- 
David

**Comment by dzaouch** [comment]
You have to extract the zip first, then drag and drop the extracted folder to the extension tab.

**Comment by drunkatheist** [comment]
I realize this. I am dragging the extracted folder.

**Comment by dzaouch** [comment]
did you already installed the version you can find on the chrome store ?

**Comment by drunkatheist** [comment]
I tried to, yeah. That may be my issue.

**Comment by drunkatheist** [comment]
If I go back to the version on the chrome store, and try to download it there, I get error: 

An error has occurred
This item is already being downloaded and added into Chrome.

so there must be some version of it on my computer, but it doesn't appear on my extensions tab. Do you know where the files might save to on my computer, so I can try to delete them before reinstalling the github version?

**Comment by ncla** [comment]
C:\Users\{USER}\AppData\Local\Google\Chrome\User Data\Default\Extensions

**Comment by drunkatheist** [comment]
Thanks! 
I didn't see a folder with the extension ID "chkhjbnahiejmehecjapfhpdfmejmolf" from the chrome store, unfortunately. I tried removing all the folders inside that extensions folder anyway, which of course disabled all of my other extensions, and tried the github install again, but got the same result.

**Comment by drunkatheist** [comment]
I did a full search for the extension ID and the only matching file was the originally downloaded crx file in 
C:\Users\{user}\AppData\Local\Google\Chrome\User Data\Webstore Downloads
I removed the crx file and this didn't help either.

**Comment by ncla** [comment]
No idea, reinstall Chrome? Though you will lose your data. 

You could try installing Chrome Cannary and try loading extension there (because it will be a seperate Chrome).

**Comment by drunkatheist** [comment]
That's a good idea, I was hesitant to reinstall before I knew for sure, but I can check if it works with Canary first. I'm late for a lecture so I'll follow up in a couple hours. Thanks for the help!

**Comment by drunkatheist** [comment]
It does work in Canary, so I guess that confirms it's an issue with my Chrome and not the extension. Thanks again to both of you!
